---
- name: Get disk space on servers
  hosts: all
  tasks:
    - name: Run df -h
      command: df -h
      register: df_output

    - name: Print output
      debug:
        var: df_output.stdout_lines

